In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
'''Loading Data'''
df = pd.read_csv("Railway Ticket Confirmation.csv")

In [3]:
'''Understanding Dataset...'''

'Understanding Dataset...'

In [4]:
df.head()

,PNR Number,Train Number,Date of Journey,Class of Travel,Quota,Source Station,Destination Station,Booking Date,Current Status,Number of Passengers,...,Booking Channel,Travel Distance,Number of Stations,Travel Time,Train Type,Seat Availability,Special Considerations,Holiday or Peak Season,Waitlist Position,Confirmation Status
0,PNR0000000000,51450,2024-09-01,3AC,General,NDLS,CSMT,2024-01-01,Confirmed,4,...,Counter,1656,17,37,Shatabdi,159,Senior Citizen,Yes,NaN,Confirmed
1,PNR0000000001,54807,2024-09-02,3AC,Premium Tatkal,MMCT,LTT,2024-01-02,Waitlisted,5,...,Mobile App,1932,18,6,Shatabdi,309,NaN,Yes,WL097,Not Confirmed
2,PNR0000000002,14396,2024-09-03,3AC,Ladies,GKP,BBS,2024-01-03,RAC,5,...,IRCTC Website,155,4,17,Express,143,NaN,Yes,NaN,Confirmed
3,PNR0000000003,20295,2024-09-04,3AC,Ladies,ASR,KOAA,2024-01-04,Waitlisted,1,...,Counter,1840,5,16,Superfast,256,Senior Citizen,No,WL011,Not Confirmed
4,PNR0000000004,48598,2024-09-05,2AC,Tatkal,MAS,SBC,2024-01-05,Confirmed,3,...,Mobile App,1766,9,32,Express,58,NaN,Yes,NaN,Confirmed

In [5]:
df.shape #30000 rows and 21 columns

(30000, 21)

In [6]:
df.columns

Index(['PNR Number', 'Train Number', 'Date of Journey', 'Class of Travel',
       'Quota', 'Source Station', 'Destination Station', 'Booking Date',
       'Current Status', 'Number of Passengers', 'Age of Passengers',
       'Booking Channel', 'Travel Distance', 'Number of Stations',
       'Travel Time', 'Train Type', 'Seat Availability',
       'Special Considerations', 'Holiday or Peak Season', 'Waitlist Position',
       'Confirmation Status'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PNR Number              30000 non-null  str
 1   Train Number            30000 non-null  int64
 2   Date of Journey         30000 non-null  str
 3   Class of Travel         30000 non-null  str
 4   Quota                   30000 non-null  str
 5   Source Station          30000 non-null  str
 6   Destination Station     30000 non-null  str
 7   Booking Date            30000 non-null  str
 8   Current Status          30000 non-null  str
 9   Number of Passengers    30000 non-null  int64
 10  Age of Passengers       30000 non-null  str
 11  Booking Channel         30000 non-null  str
 12  Travel Distance         30000 non-null  int64
 13  Number of Stations      30000 non-null  int64
 14  Travel Time             30000 non-null  int64
 15  Train Type              30000 non-null  str
 16  Seat Availability       30000 non-null  int64
 17  Special Considerations  20045 non-null  str
 18  Holiday or Peak Season  30000 non-null  str
 19  Waitlist Position       10053 non-null  str
 20  Confirmation Status     30000 non-null  str
dtypes: int64(6), str(15)
memory usage: 4.8 MB

In [8]:
df.describe()

,Train Number,Number of Passengers,Travel Distance,Number of Stations,Travel Time,Seat Availability
count,30000.000000,30000.000000,30000.000000,30000.00000,30000.000000,30000.000000
mean,55039.057000,3.006033,1022.616300,10.47540,24.589933,248.493767
std,26073.496614,1.414472,561.967777,5.20616,13.279498,144.248284
min,10000.000000,1.000000,50.000000,2.00000,2.000000,0.000000
25%,32361.750000,2.000000,536.000000,6.00000,13.000000,124.000000
50%,55279.500000,3.000000,1023.000000,10.00000,25.000000,248.000000
75%,77699.750000,4.000000,1509.000000,15.00000,36.000000,373.000000
max,99997.000000,5.000000,1999.000000,19.00000,47.000000,499.000000

In [9]:
'''Checking Null/Duplicate Values...'''

'Checking Null/Duplicate Values...'

In [10]:
df.isnull().sum() #So, Special Considerations and Waitlist Position has null values...

PNR Number                    0
Train Number                  0
Date of Journey               0
Class of Travel               0
Quota                         0
Source Station                0
Destination Station           0
Booking Date                  0
Current Status                0
Number of Passengers          0
Age of Passengers             0
Booking Channel               0
Travel Distance               0
Number of Stations            0
Travel Time                   0
Train Type                    0
Seat Availability             0
Special Considerations     9955
Holiday or Peak Season        0
Waitlist Position         19947
Confirmation Status           0
dtype: int64

In [11]:
df.duplicated().sum() #No duplicate values...

#If there is few duplicate values then drop with :-
#df.drop_duplicates()

np.int64(0)

In [12]:
'''Cleaning Null Values :-
    i.e.
        Special Considerations     9955
        and Waitlist Position      19947 '''

'Cleaning Null Values :-\n    i.e.\n        Special Considerations     9955\n        and Waitlist Position      19947 '

In [13]:
#Never Clean Original Dataframe use a clone or copy version

df_clean = df.copy()

In [14]:
#PNR of Train must be unique so we check it also
df_clean["PNR Number"].nunique()

30000

In [15]:
df_clean.head(3)

,PNR Number,Train Number,Date of Journey,Class of Travel,Quota,Source Station,Destination Station,Booking Date,Current Status,Number of Passengers,...,Booking Channel,Travel Distance,Number of Stations,Travel Time,Train Type,Seat Availability,Special Considerations,Holiday or Peak Season,Waitlist Position,Confirmation Status
0,PNR0000000000,51450,2024-09-01,3AC,General,NDLS,CSMT,2024-01-01,Confirmed,4,...,Counter,1656,17,37,Shatabdi,159,Senior Citizen,Yes,NaN,Confirmed
1,PNR0000000001,54807,2024-09-02,3AC,Premium Tatkal,MMCT,LTT,2024-01-02,Waitlisted,5,...,Mobile App,1932,18,6,Shatabdi,309,NaN,Yes,WL097,Not Confirmed
2,PNR0000000002,14396,2024-09-03,3AC,Ladies,GKP,BBS,2024-01-03,RAC,5,...,IRCTC Website,155,4,17,Express,143,NaN,Yes,NaN,Confirmed

In [16]:
#What percent of data is missing from dataset

missing = df.isnull().sum()

missing_percentage = ( missing / (len(df_clean))) * 100

pd.DataFrame({
    "Missing Values": missing,
    "Missing %": missing_percentage
})

                        Missing Values  Missing %
PNR Number                           0   0.000000
Train Number                         0   0.000000
Date of Journey                      0   0.000000
Class of Travel                      0   0.000000
Quota                                0   0.000000
Source Station                       0   0.000000
Destination Station                  0   0.000000
Booking Date                         0   0.000000
Current Status                       0   0.000000
Number of Passengers                 0   0.000000
Age of Passengers                    0   0.000000
Booking Channel                      0   0.000000
Travel Distance                      0   0.000000
Number of Stations                   0   0.000000
Travel Time                          0   0.000000
Train Type                           0   0.000000
Seat Availability                    0   0.000000
Special Considerations            9955  33.183333
Holiday or Peak Season               0   0.000000
Waitlist Position                19947  66.490000
Confirmation Status                  0   0.000000

In [17]:
#Special Considerations has 9955 null values represented by NaN
#Here it means there is no special consideration for the passenger

df_clean['Special Considerations'] = df_clean['Special Considerations'].fillna('No Special Consideration')

In [18]:
#Waitlist Position has 19947 null values represnted by NaN
#Here it means passenger is not waitlisted so we replace it with 0 means in clean numeric value or make another column name was waitlisted in boolean form

df_clean["Was Waitlisted"] = df_clean["Waitlist Position"].notna()

In [19]:
df_clean['Waitlist Position'] = df_clean['Waitlist Position'].fillna('WL0')

In [20]:
df_clean['Waitlist Position'] = df_clean['Waitlist Position'].str.replace('WL', '')

df_clean['Waitlist Position'] = df_clean['Waitlist Position'].astype(int)

In [21]:
#Check updated or not
df_clean.isnull().sum()

PNR Number                0
Train Number              0
Date of Journey           0
Class of Travel           0
Quota                     0
Source Station            0
Destination Station       0
Booking Date              0
Current Status            0
Number of Passengers      0
Age of Passengers         0
Booking Channel           0
Travel Distance           0
Number of Stations        0
Travel Time               0
Train Type                0
Seat Availability         0
Special Considerations    0
Holiday or Peak Season    0
Waitlist Position         0
Confirmation Status       0
Was Waitlisted            0
dtype: int64

In [22]:
'''Check Data Types'''

'Check Data Types'

In [23]:
df_clean.dtypes

PNR Number                  str
Train Number              int64
Date of Journey             str
Class of Travel             str
Quota                       str
Source Station              str
Destination Station         str
Booking Date                str
Current Status              str
Number of Passengers      int64
Age of Passengers           str
Booking Channel             str
Travel Distance           int64
Number of Stations        int64
Travel Time               int64
Train Type                  str
Seat Availability         int64
Special Considerations      str
Holiday or Peak Season      str
Waitlist Position         int64
Confirmation Status         str
Was Waitlisted             bool
dtype: object

In [24]:
#Here we see Date of Journey and Booking Date are in string form so convert it into datetime 

df_clean['Date of Journey'] = pd.to_datetime(df_clean['Date of Journey'])

df_clean["Booking Date"] = pd.to_datetime(df_clean["Booking Date"])

In [25]:
df_clean.dtypes

PNR Number                           str
Train Number                       int64
Date of Journey           datetime64[us]
Class of Travel                      str
Quota                                str
Source Station                       str
Destination Station                  str
Booking Date              datetime64[us]
Current Status                       str
Number of Passengers               int64
Age of Passengers                    str
Booking Channel                      str
Travel Distance                    int64
Number of Stations                 int64
Travel Time                        int64
Train Type                           str
Seat Availability                  int64
Special Considerations               str
Holiday or Peak Season               str
Waitlist Position                  int64
Confirmation Status                  str
Was Waitlisted                      bool
dtype: object

In [26]:
df_clean.describe().T # T means Transpose rows to column and column to rows

,count,mean,min,25%,50%,75%,max,std
Train Number,30000.0,55039.057,10000.0,32361.75,55279.5,77699.75,99997.0,26073.496614
Date of Journey,30000,2065-09-25 12:00:00,2024-09-01 00:00:00,2045-03-14 18:00:00,2065-09-25 12:00:00,2086-04-08 06:00:00,2106-10-21 00:00:00,NaN
Booking Date,30000,2065-01-24 12:00:00,2024-01-01 00:00:00,2044-07-13 18:00:00,2065-01-24 12:00:00,2085-08-07 06:00:00,2106-02-19 00:00:00,NaN
Number of Passengers,30000.0,3.006033,1.0,2.0,3.0,4.0,5.0,1.414472
Travel Distance,30000.0,1022.6163,50.0,536.0,1023.0,1509.0,1999.0,561.967777
Number of Stations,30000.0,10.4754,2.0,6.0,10.0,15.0,19.0,5.20616
Travel Time,30000.0,24.589933,2.0,13.0,25.0,36.0,47.0,13.279498
Seat Availability,30000.0,248.493767,0.0,124.0,248.0,373.0,499.0,144.248284
Waitlist Position,30000.0,33.316633,0.0,0.0,0.0,49.0,200.0,57.698042

In [27]:
'''Checking the column that must not be 0 or less then 0'''

'''
    Number of Passengers
    Age of Passengers
    Travel Distance
    Number of Stations
    Travel Time
    Seat Availability
'''

'\n    Number of Passengers\n    Age of Passengers\n    Travel Distance\n    Number of Stations\n    Travel Time\n    Seat Availability\n'

In [28]:
df_clean[df_clean["Travel Distance"] < 0]

Empty DataFrame
Columns: [PNR Number, Train Number, Date of Journey, Class of Travel, Quota, Source Station, Destination Station, Booking Date, Current Status, Number of Passengers, Age of Passengers, Booking Channel, Travel Distance, Number of Stations, Travel Time, Train Type, Seat Availability, Special Considerations, Holiday or Peak Season, Waitlist Position, Confirmation Status, Was Waitlisted]
Index: []

[0 rows x 22 columns]

In [29]:
df_clean[df_clean["Number of Passengers"] <= 0]

Empty DataFrame
Columns: [PNR Number, Train Number, Date of Journey, Class of Travel, Quota, Source Station, Destination Station, Booking Date, Current Status, Number of Passengers, Age of Passengers, Booking Channel, Travel Distance, Number of Stations, Travel Time, Train Type, Seat Availability, Special Considerations, Holiday or Peak Season, Waitlist Position, Confirmation Status, Was Waitlisted]
Index: []

[0 rows x 22 columns]

In [30]:
df_clean[df_clean["Seat Availability"] < 0]

Empty DataFrame
Columns: [PNR Number, Train Number, Date of Journey, Class of Travel, Quota, Source Station, Destination Station, Booking Date, Current Status, Number of Passengers, Age of Passengers, Booking Channel, Travel Distance, Number of Stations, Travel Time, Train Type, Seat Availability, Special Considerations, Holiday or Peak Season, Waitlist Position, Confirmation Status, Was Waitlisted]
Index: []

[0 rows x 22 columns]

In [31]:
'''Checking Categorical Values'''
'''
    Class of Travel
    Quota
    Current Status
    Booking Channel
    Train Type
    Confirmation Status
'''

'\n    Class of Travel\n    Quota\n    Current Status\n    Booking Channel\n    Train Type\n    Confirmation Status\n'

In [32]:
df_clean["Class of Travel"].value_counts()

Class of Travel
Sleeper    7613
1AC        7482
3AC        7460
2AC        7445
Name: count, dtype: int64

In [33]:
df_clean["Quota"].value_counts()

Quota
Ladies            7655
General           7501
Tatkal            7444
Premium Tatkal    7400
Name: count, dtype: int64

In [34]:
df_clean["Current Status"].value_counts()

Current Status
Waitlisted    10053
RAC           10029
Confirmed      9918
Name: count, dtype: int64

In [35]:
df_clean["Booking Channel"].value_counts()

Booking Channel
IRCTC Website    10040
Mobile App       10023
Counter           9937
Name: count, dtype: int64

In [36]:
df_clean["Train Type"].value_counts()

Train Type
Shatabdi     7621
Rajdhani     7593
Express      7413
Superfast    7373
Name: count, dtype: int64

In [37]:
df_clean["Confirmation Status"].value_counts()

Confirmation Status
Confirmed        19947
Not Confirmed    10053
Name: count, dtype: int64

In [38]:
'''Save your Cleaned Data'''

'Save your Cleaned Data'

In [39]:
df_clean.to_csv("Railway_Cleaned.csv",index=False)